steps:
  # Step 1: Build the frontend service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/hawthorne-notifications-frontend',
      '--build-arg', 'REACT_APP_FRONTEND_BASE_URL=$REACT_APP_FRONTEND_BASE_URL',
      '.'
    ]

  # Step 2: Build the backend service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/hawthorne-notifications-app',
      '.'
    ]

  # Step 3: Deploy the backend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'hawthorne-notifications-backend',
      '--image', 'gcr.io/$PROJECT_ID/hawthorne-notifications-app',
      '--platform', 'managed',
      '--region', 'us-west1',
      '--memory', '128Mi',
      '--cpu', '0.5',
      '--set-env-vars', 'GMAIL_PASSWORD=${_GMAIL_PASSWORD},env=prod',
      '--allow-unauthenticated'
    ]

  # Step 4: Deploy the frontend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'hawthorne-notifications-frontend',
      '--image', 'gcr.io/$PROJECT_ID/hawthorne-notifications-frontend',
      '--platform', 'managed',
      '--region', 'us-central1', # Adjust the region as needed
      '--memory', '128Mi',
      '--cpu', '0.5',
      '--set-env-vars', 'REACT_APP_BACKEND_BASE_URL=http://backend:8080',
      '--allow-unauthenticated'
    ]

substitutions:
  _GMAIL_PASSWORD: $

secrets:
- kmsKeyName: projects/$PROJECT_ID/locations/global/keyRings/$KEYRING_NAME/cryptoKeys/$KEY_NAME
  secretEnv:
    GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS

images:
  - gcr.io/$PROJECT_ID/hawthorne-notifications-frontend
  - gcr.io/$PROJECT_ID/hawthorne-notifications-app
