---
apiVersion: google.devtools.cloudbuild.v1.Build
steps:
  # Step 1: Build the frontend service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/hawthorne-notifications-repo/hawthorne-notifications-frontend:latest',
      '--platform', 'linux/amd64',
      '.'
    ]

  # Step 2: Build the backend service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/hawthorne-notifications-repo/hawthorne-notifications-app:latest',
      '--platform', 'linux/amd64',
      '.'
    ]

  # Step 3: Push the frontend image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-west1-docker.pkg.dev/$PROJECT_ID/hawthorne-notifications-repo/hawthorne-notifications-frontend:latest'
    ]

  # Step 4: Push the backend image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-west1-docker.pkg.dev/$PROJECT_ID/hawthorne-notifications-repo/hawthorne-notifications-app:latest'
    ]

  # Step 5: Deploy the Knative Service for frontend and backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set run/region us-west1
        cat frontend.yaml | gcloud run services update -

images:
  - us-west1-docker.pkg.dev/$PROJECT_ID/hawthorne-notifications-repo/hawthorne-notifications-frontend:latest
  - us-west1-docker.pkg.dev/$PROJECT_ID/hawthorne-notifications-repo/hawthorne-notifications-app:latest

options:
  logging: CLOUD_LOGGING_ONLY
