---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hawthorne-notifications-frontend
  labels:
    cloud.googleapis.com/location: us-west1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/container-dependencies: '{"hawthorne-notifications-frontend-1":["hawthorne-notifications-app-1"]}'
    spec:
      containerConcurrency: 500
      timeoutSeconds: 30
      serviceAccountName: go-hawthorne-notifications-ser@hawthorne-notifications.iam.gserviceaccount.com
      containers:
        - name: hawthorne-notifications-frontend-1
          image: us-west1-docker.pkg.dev/hawthorne-notifications/hawthorne-notifications-repo/hawthorne-notifications-frontend:latest
          ports:
            - name: http1
              containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_BASE_URL
              value: http://localhost:8080
            - name: env
              value: prod
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          startupProbe:
            timeoutSeconds: 1
            periodSeconds: 1
            failureThreshold: 2
            tcpSocket:
              port: 3000
        - name: hawthorne-notifications-app-1
          image: us-west1-docker.pkg.dev/hawthorne-notifications/hawthorne-notifications-repo/hawthorne-notifications-app:latest
          env:
            - name: env
              value: prod
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GMAIL_PASSWORD
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          startupProbe:
            timeoutSeconds: 1
            periodSeconds: 1
            failureThreshold: 2
            tcpSocket:
              port: 8080
